name: Linting
on: [push, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.8'
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Linting
      run: |
          pip install pylint==2.4.4
          python -m pylint --reports=n --rcfile=.pylintrc certbot_dns_hetzner
